<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9411" started-at="2017-09-20T05:59:43Z" finished-at="2017-09-20T05:59:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9411" started-at="2017-09-20T05:59:43Z" finished-at="2017-09-20T05:59:53Z">
      <class name="NewTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:NewTest@3e6fa38a]" name="beforeTest" is-config="true" duration-ms="2494" started-at="2017-09-20T02:59:43Z" finished-at="2017-09-20T02:59:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="App_Title_CelFar2()[pri:0, instance:NewTest@3e6fa38a]" name="App_Title_CelFar2" duration-ms="2311" started-at="2017-09-20T02:59:46Z" finished-at="2017-09-20T02:59:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- App_Title_CelFar2 -->
        <test-method status="FAIL" signature="Page_Title_CelFar()[pri:0, instance:NewTest@3e6fa38a]" name="Page_Title_CelFar" duration-ms="496" started-at="2017-09-20T02:59:48Z" finished-at="2017-09-20T02:59:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CelFar] but found [Conversor CelFar]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CelFar] but found [Conversor CelFar]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at NewTest.Page_Title_CelFar(NewTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Page_Title_CelFar -->
        <test-method status="FAIL" signature="conL_1234567()[pri:0, instance:NewTest@3e6fa38a]" name="conL_1234567" duration-ms="630" started-at="2017-09-20T02:59:49Z" finished-at="2017-09-20T02:59:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [El valor ingresado es muy largo2] but found [El valor ingresado es muy largo]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [El valor ingresado es muy largo2] but found [El valor ingresado es muy largo]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at NewTest.convertLong(NewTest.java:59)
	at NewTest.conL_1234567(NewTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- conL_1234567 -->
        <test-method status="PASS" signature="con_0()[pri:0, instance:NewTest@3e6fa38a]" name="con_0" duration-ms="594" started-at="2017-09-20T02:59:49Z" finished-at="2017-09-20T02:59:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- con_0 -->
        <test-method status="PASS" signature="con_10()[pri:0, instance:NewTest@3e6fa38a]" name="con_10" duration-ms="592" started-at="2017-09-20T02:59:50Z" finished-at="2017-09-20T02:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- con_10 -->
        <test-method status="PASS" signature="con_20()[pri:0, instance:NewTest@3e6fa38a]" name="con_20" duration-ms="583" started-at="2017-09-20T02:59:51Z" finished-at="2017-09-20T02:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- con_20 -->
        <test-method status="PASS" signature="con_m300()[pri:0, instance:NewTest@3e6fa38a]" name="con_m300" duration-ms="585" started-at="2017-09-20T02:59:51Z" finished-at="2017-09-20T02:59:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- con_m300 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:NewTest@3e6fa38a]" name="afterTest" is-config="true" duration-ms="1103" started-at="2017-09-20T02:59:52Z" finished-at="2017-09-20T02:59:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
